export enum IconName {
  HOME = 'home',
  FORUM = 'forum',
  MAIL = 'mail',
  CAMPAIGN = 'campaign',
  GROUP = 'group',
  TASK = 'task',
  PAID = 'paid',
  FOLDER = 'folder',
  SLOW_MOTION_VIDEO = 'slow_motion_video',
  INSERT_CHART = 'insert_chart',
  MENU = 'menu',
  MENU_OPEN = 'menu_open',
  SEARCH = 'search',
  EVENT = 'event',
  NOTIFICATIONS = 'notifications',
  SETTINGS = 'settings',
  CHEVRON_LEFT = 'chevron_left',
  CHEVRON_RIGHT = 'chevron_right',
  NORTH_EAST = 'north_east',
  PHONE = 'phone',
  CHAT = 'chat',
  EDIT = 'edit',
  MORE_VERT = 'more_vert',
  UNFOLD_MORE = 'unfold_more',
}
